### ISSUE TITLE
Failed to activate the autotag-junk-control package

### ISSUE THREAD

**Issue by themestechnology** [101arg101/Autotag-Junk-Control#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [autotag-junk-control](https://github.com/101arg101/Autotag-Junk-Control) package, v0.1.2
### Stack Trace

Failed to activate the autotag-junk-control package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/home/web/.atom/packages/autotag-junk-control/lib/autotag-junk-control.coffee:20:23)
  at Package.module.exports.Package.activateNow (/opt/atom/resources/app.asar/src/package.js:240:19)
  at /opt/atom/resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/opt/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/opt/atom/resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/opt/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/opt/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/opt/atom/resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/opt/atom/resources/app.asar/src/window-event-handler.js:150:33)
  at HTMLDocument.handler (/opt/atom/resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/opt/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```
### Commands

```
     -2:20.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:19.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:26.9.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:26.1.0 application:new-file (atom-text-editor.editor.is-focused)
     -1:24.8.0 core:paste (atom-text-editor.editor.is-focused)
     -1:24.2.0 core:undo (atom-text-editor.editor.is-focused)
     -1:17.8.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:54.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:51.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:47.8.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:44.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:40.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:39.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:24.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:07.4.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.4.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "metrics"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
auto-detect-indentation, v0.4.2
auto-indent, v0.5.0
autotag-junk-control, v0.1.2
color-picker, v2.0.7
indent-guide-improved, v1.2.0
navigate-indent, v0.1.0
w3c-validation, v0.2.0

# Dev
No dev packages
```

**Comment by 101arg101** [comment]
I created this package when I was first toying around with Atom and I couldn't find any packages that let me type the way I normally do from my other text editor. Since then, I moved back to my original editor, because there were bugs that prevented me from using Atom efficiently. After half a year, I suppose I can take another look at it.

**Comment by 101arg101** [comment]
Too busy to update this package to work with modern Atom.io. I instead unpublished the package. Sorry you couldn't get this. If you want to create your own package, you can just grab all the code you see here and update it yourself.
